# Generated by Django 4.0.4 on 2022-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('campo', models.TextField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
